import type { CairnGraph } from './graph.js';
import type { NodeType } from './types.js';

/** Map an arbitrary node id to a Mermaid-safe identifier. */
function mermaidId(id: string): string {
  return `n_${id.replace(/[^a-zA-Z0-9]/g, '_')}`;
}

/** Mermaid labels are double-quoted; swap any inner double quotes for single. */
function escapeLabel(text: string): string {
  return text.replace(/"/g, "'");
}

/** Render the live graph as a Mermaid flowchart (superseded nodes omitted). */
export function renderMermaid(graph: CairnGraph): string {
  const doc = graph.toJSON();
  const live = doc.nodes.filter((node) => node.status !== 'superseded');
  const liveIds = new Set(live.map((node) => node.id));
  const lines: string[] = ['flowchart TD'];
  for (const node of live) {
    lines.push(`  ${mermaidId(node.id)}["${escapeLabel(`${node.type}: ${node.title}`)}"]`);
  }
  for (const edge of doc.edges) {
    if (!liveIds.has(edge.from) || !liveIds.has(edge.to)) continue;
    lines.push(`  ${mermaidId(edge.from)} -->|${edge.type}| ${mermaidId(edge.to)}`);
  }
  return lines.join('\n');
}

const SECTIONS: ReadonlyArray<{ heading: string; type: NodeType }> = [
  { heading: 'Goals', type: 'goal' },
  { heading: 'Requirements', type: 'requirement' },
  { heading: 'Decisions', type: 'decision' },
  { heading: 'Components', type: 'component' },
  { heading: 'Constraints', type: 'constraint' },
  { heading: 'Open Questions', type: 'question' },
  { heading: 'Risks', type: 'risk' },
];

/** Render the graph as a human-readable narrative design document. */
export function renderDesignDoc(graph: CairnGraph): string {
  const title = graph.query({ type: 'goal' })[0]?.title ?? 'Cairn Project';
  const lines: string[] = [
    `# ${title}`,
    '',
    '> Generated by Cairn from the project knowledge graph.',
  ];

  for (const section of SECTIONS) {
    const nodes = graph.query({ type: section.type });
    if (nodes.length === 0) continue;
    lines.push('', `## ${section.heading}`);
    for (const node of nodes) {
      const status = node.status !== 'open' ? ` _(${node.status})_` : '';
      const body = node.body ? ` — ${node.body}` : '';
      lines.push(`- **${node.title}**${status}${body}`);
    }
  }

  lines.push('', '## Graph', '', '```mermaid', renderMermaid(graph), '```');
  return lines.join('\n');
}
